version: '3.8'
services:
  dashboard:
    build: ./dashboard
    ports:
      - "80:3000"
    restart: always
  backend:
    build: 
      context: ./backend
      args:
        PORT: 3333
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pv
      DB_USER: pv-user
      DB_PASSWORD: pvuser123!!
      AHOY_DTU_URL: http://192.168.178.37
      STORING_INTERVAL: 5
    networks:
      - backend
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pv-user
      POSTGRES_PASSWORD: pvuser123!!
      POSTGRES_DB: pv
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@me.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - network
volumes:
  local_pgdata:
  pgadmin-data:
networks:
  backend:
    external: true
    name: pv-network
  network:
    driver: bridge
    name: pv-network